#!/usr/bin/env python3

import gam
#GAMCFG = '/Library/Application Support/GAM/gam.cfg'
GAMCFG = '/Users/Ross/.gam/gam.cfg'

gam.SetGlobalVariables(GAMCFG)
print('\nCustomersGet')
result, status = gam.CustomersGet(None)
print(status, result)
print('\nDomainsGet')
result, status = gam.DomainsGet(None, None)
print(status, result)
print('\nDomainsList')
result, status = gam.DomainsList(None)
print(status, result)
print('\nGroupsGet')
result, status = gam.GroupsGet(groupKey='testgroup@rdschool.org', fields='*')
print(status, result)
print('\nGroupsList')
result, status = gam.GroupsList(fields='email,directMembersCount')
print(status, result)
print('\nMembersGet')
result, status = gam.MembersGet('testgroup@rdschool.org', 'testuser1@rdschool.org', fields='*')
print(status, result)
print('\nMembersList')
result, status = gam.MembersList('testgroup@rdschool.org', fields='email,id,role,status,type,delivery_settings')
print(status, result)
print('\nOrgunitsInsert')
result, status = gam.OrgunitsInsert(None, body={'name': 'Fribble', 'parentOrgUnitPath': '/Test'})
print(status, result)
print('\nOrgunitsGet')
result, status = gam.OrgunitsGet(None, '/Test/Fribble')
print(status, result)
print('\nOrgunitsUpdate')
result, status = gam.OrgunitsUpdate(None, '/Test/Fribble', body={'description': 'Fribble'})
print(status, result)
print('\nOrgunitsList')
result, status = gam.OrgunitsList(None)
print(status, result)
print('\nOrgunitsDelete')
result, status = gam.OrgunitsDelete(None, '/Test/Fribble')
print(status, result)
print('\nUsersGet')
result, status = gam.UsersGet('testuser1@rdschool.org', fields='*')
print(status, result)
print('\nUsersList')
result, status = gam.UsersList(query='orgUnitPath:/Test', fields='primaryEmail,includeInGlobalAddressList,suspended')
print(status, result)
